name: PR CI — Dependency updates

on:
  pull_request:
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint || true

      - name: Run tests
        run: pnpm run test:run

      - name: Build
        run: pnpm run build

  automerge-dependabot:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto-merge Dependabot when checks pass
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({ owner: context.repo.owner, repo: context.repo.repo, pull_number: context.issue.number });
            const checks = await github.rest.checks.listForRef({ owner: context.repo.owner, repo: context.repo.repo, ref: pr.data.head.sha });
            const allSuccess = checks.data.check_runs.every(c => c.conclusion === 'success' || c.conclusion === null);
            if (allSuccess) {
              await github.rest.pulls.merge({ owner: context.repo.owner, repo: context.repo.repo, pull_number: context.issue.number, merge_method: 'squash' });
            } else {
              core.info('Not all checks passed yet; skipping auto-merge.');
            }
